db:
  environment:
    POSTGRES_DB: saatiobot
    POSTGRES_PASSWORD: saatiobot
    POSTGRES_USER: saatiobot
  image: postgres:9.4
  volumes:
  - /opt/saatiobot/dbdata:/var/lib/postgresql/data
saatiobot:
  environment:
    DATABASE_URL: postgres://saatiobot:saatiobot@db/saatiobot
  image: mrako/saatiobot
  links:
  - db:db
